#!/bin/sh

set -e

uname=`uname`
platform="unknown"
if [[ $uname == "Darwin" ]]; then
   platform="macos"
elif [[ $uname == "Linux" ]]; then
   platform="linux"
fi

if [ "$platform" == "macos" ]; then
  ./setup-macos
fi

./setup-bash
./setup-git
./setup-vim
