#!/bin/sh

set -e

source setup-helpers

# Install git
# TODO: Make this cross-platform
brew install git

install_dotfile "gitignore"

git config --global alias.br branch
git config --global alias.cm commit
git config --global alias.cmm "commit -m"
git config --global alias.co checkout
git config --global alias.lol "log --graph --decorate --pretty=oneline --abbrev-commit"
git config --global alias.lola "log --graph --decorate --pretty=oneline --abbrev-commit --all"
git config --global alias.ls ls-files
git config --global alias.st status

git config --global color.ui true

git config --global core.autocrlf input
git config --global core.editor vim
git config --global core.eol lf
git config --global core.excludesfile "$HOME/.gitignore"

git config --global credential.helper osxkeychain

git config --global push.default current

git config --global url.https://.insteadOf git://

git config --global user.email "mj@mjackson.me"
git config --global user.name "Michael Jackson"
